### ISSUE TITLE
KeyError: 'BENCHMARK'

### ISSUE THREAD

**Issue by jeffxhsiao** [OpenDriveLab/ThinkTwice#18]
Hello, I want to prepare the dataset and run `CUDA_VISIBLE_DEVICES=0 nohup bash ./leaderboard/scripts/collect_data.sh 22023 22033 town05_00 False True roach_ap_agent_data_collection all_towns_traffic_scenarios_no256  2>&1 > town05_00.log &`
However, the town05_00.log appear the following error:
Traceback (most recent call last):
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 40, in <module>
    from leaderboard.utils.statistics_manager import StatisticsManager
  File "/home/user/ThinkTwice-main/leaderboard/leaderboard/utils/statistics_manager.py", line 28, in <module>
    if os.environ["BENCHMARK"] == "longest6":
  File "/home/user/anaconda3/envs/thinktwice/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'BENCHMARK'

How can I fix it? Thanks.

**Comment by jiaxiaosong1002** [comment]
@jeffxhsiao  Sorry. It's a bug introduced by an update. You could add a BENCHMARK environment variable with any value other than "town05long" and "longest6".  I have updated the scripts as well.

**Comment by jeffxhsiao** [comment]
It works! Thank you.
