### ISSUE TITLE
Error when collecting data

### ISSUE THREAD

**Issue by exiawsh** [OpenDriveLab/ThinkTwice#7]
> Running the route
initialized
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server "localhost:10.0"
      after 4060 requests (4060 known processed) with 0 events remaining.
terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
Signal 6 caught.
/data/carla/CarlaUE4.sh: line 5:   555 Segmentation fault      "$UE4_PROJECT_ROOT/CarlaUE4/Binaries/Linux/CarlaUE4-Linux-Shipping" CarlaUE4 $@
Traceback (most recent call last):
  File "/data/ThinkTwice/leaderboard/leaderboard/envs/sensor_interface.py", line 244, in get_data
    sensor_data = self._new_data_buffers.get(True, self._queue_timeout)
  File "/home/wangshihao02/.conda/envs/thinktwice/lib/python3.7/queue.py", line 178, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/ThinkTwice/leaderboard/leaderboard/scenarios/scenario_manager.py", line 154, in _tick_scenario
    ego_action = self._agent()
  File "/data/ThinkTwice/leaderboard/leaderboard/autoagents/agent_wrapper.py", line 82, in __call__
    return self._agent()
  File "/data/ThinkTwice/leaderboard/leaderboard/autoagents/autonomous_agent.py", line 104, in __call__
    input_data = self.sensor_interface.get_data()
  File "/data/ThinkTwice/leaderboard/leaderboard/envs/sensor_interface.py", line 248, in get_data
    raise SensorReceivedNoData("A sensor took too long to send their data")
leaderboard.envs.sensor_interface.SensorReceivedNoData: A sensor took too long to send their data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 542, in main
    leaderboard_evaluator.run(arguments)
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 462, in run
    self._load_and_run_scenario(args, config)
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 416, in _load_and_run_scenario
    self.manager.run_scenario()
  File "/data/ThinkTwice/leaderboard/leaderboard/scenarios/scenario_manager.py", line 138, in run_scenario
    self._tick_scenario(timestamp)
  File "/data/ThinkTwice/leaderboard/leaderboard/scenarios/scenario_manager.py", line 158, in _tick_scenario
    raise RuntimeError(e)
RuntimeError: A sensor took too long to send their data
Collect Done
 Hi, thanks for the great work!
I get a runtime error when collecting the data.
Would you please provide some advise to avoid this?

**Comment by jiaxiaosong1002** [comment]
@exiawsh 
Hi. "leaderboard.envs.sensor_interface.SensorReceivedNoData: A sensor took too long to send their data". It might be because 
1. there is too much CARLA in one single GPU
2. not enough CPU in one single machine
3. The cooresponding CARLA simulator is crashed
You should monitor GPU and CPU.

However, it is still unavoidable to encounter CARLA crash problem. Note that in our preprocess [code](https://github.com/OpenDriveLab/ThinkTwice/blob/main/dataset/tools/generate_metadata.py), we could utilze the collected data of those crashed routes (without json). However, you should keep as much as possible completed routes to improve the quality of the data.
